# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-02 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('AC_enabled', 'Set air condition status'), ('AC_temperature', 'Set air condition temperature')], max_length=30)),
                ('value', models.CharField(max_length=50)),
            ],
        ),
    ]
