# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-05 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160302_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloatData',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('AC_enabled', 'Set air condition status'), ('AC_temperature', 'Set air condition temperature'), ('AC_timer', 'Set activation time for the AC')], max_length=30, primary_key=True, serialize=False),
        ),
    ]
