# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-05 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160405_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooleanData',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('value', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='StringData',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=200)),
            ],
        ),
    ]
