# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-22 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_booleandata_stringdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorMessage',
            fields=[
                ('errno', models.IntegerField(choices=[(0, 'Unknown error'), (1, 'Communication error with the PI'), (2, 'Some error occured on the PI'), (3, 'Failed to collect car data'), (4, 'An error occurred on the PI'), (5, 'An error occurred on the PI'), (6, 'The car battery is too low to start AC'), (7, 'The car battery is too low. AC has been turned off')], primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=100)),
            ],
        ),
    ]
